practice

diff --git a/05-functions-sh b/05-functions-sh
--- a/05-functions-sh
+++ b/05-functions-sh
@@ -26,7 +26,7 @@ userid=$(id -u)
 LOGS_FOLDER="/var/log/shell-script"
 LOGS_FILE="$LOGS_FOLDER/$0.log"
  if [ $userid -ne 0 ]; then
-   echo "please run this script with root access"
+   echo "please run this script with root access" | tee -a $LOGS_FILE
    exit 1
 fi
 
@@ -34,14 +34,14 @@ mkdir -p $LOGS_FOLDER
 
 VALIDATE(){
     if [ $1 -ne 0 ]; then
-    echo "$2......failure"
+    echo "$2......failure". | tee -a $LOGS_FILE
     else
-    echo "$2.....success"
+    echo "$2.....success". | tee -a $LOGS_FILE
     fi
 }
 
-dnf install nginx -y &>>$LOGS_FILE
-VALIDATE $? "installing nginx"
+dnf install nginx -y &>>$LOGS_FILE | tee -a $LOGS_FILE
+VALIDATE $? "installing nginx"  | tee -a $LOGS_FILE
 
-dnf remove nginx -y &>>$LOGS_FILE
-VALIDATE $? "removing nginx"
+dnf remove nginx -y &>>$LOGS_FILE | tee -a $LOGS_FILE
+VALIDATE $? "removing nginx" | tee -a $LOGS_FILE
