practice

diff --git a/05-functions-sh b/05-functions-sh
--- a/05-functions-sh
+++ b/05-functions-sh
@@ -1,10 +1,36 @@
 #!/bin/bash
 
+# userid=$(id -u)
+#  if [ $userid -ne 0 ]; then
+#    echo "please run this script with root access"
+#    exit 1
+# fi
+
+# VALIDATE(){
+#     if [ $1 -ne 0 ]; then
+#     echo "$2......failure"
+#     else
+#     echo "$2.....success"
+#     fi
+# }
+
+# dnf install nginx -y
+# VALIDATE $? "installing nginx"
+
+# dnf remove nginx -y
+# VALIDATE $? "removing nginx"
+
+
+
 userid=$(id -u)
+LOGS_FOLDER="/var/log/shell-script"
+LOGS_FILE="$LOGS_FOLDER/$0.log"
  if [ $userid -ne 0 ]; then
    echo "please run this script with root access"
    exit 1
 fi
+
+mkdir -p $LOGS_FOLDER
 
 VALIDATE(){
     if [ $1 -ne 0 ]; then
@@ -14,8 +40,8 @@ VALIDATE(){
     fi
 }
 
-dnf install nginx -y
+dnf install nginx -y &>>$LOGS_FILE
 VALIDATE $? "installing nginx"
 
-dnf remove nginx -y
+dnf remove nginx -y &>>$LOGS_FILE
 VALIDATE $? "removing nginx"
